import turtle as tl
import math
def triangle(x, y, z, color):
    tl.up()
    tl.goto(x, y)
    tl.down()
    tl.color(color)
    tl.begin_fill()
    tl.left(45)
    tl.fd(z * math.sqrt(2) / 2)
    tl.left(135)
    tl.fd(z)
    tl.left(135)
    tl.fd(z * math.sqrt(2) / 2)
    tl.end_fill()
def square(x, y, z, color):
    tl.up()
    tl.goto(x, y)
    tl.down()
    tl.color(color)
    tl.begin_fill()
    tl.fd(z)
    tl.right(90)
    tl.fd(z)
    tl.right(90)
    tl.fd(z)
    tl.right(90)
    tl.fd(z)
    tl.right(90)
    tl.end_fill()
def parallelogram(x, y, z, color):
     tl.up()
     tl.goto(x, y)
     tl.down()
     tl.color(color)
     tl.begin_fill()
     tl.left(45)
     tl.fd(z * math.sqrt(2) / 2)
     tl.right(45)
     tl.fd(z)
     tl.right(135)
     tl.fd(z * math.sqrt(2) / 2)
     tl.right(45)
     tl.fd(z)
     tl.end_fill()
def fish():
    tl.left(45)
    square(0, 0, 50,'orange')
    tl.right(270)
    triangle(50 * math.sqrt(2), 100, 2*50*math.sqrt(2), 'red' )
    tl.right(45)
    triangle(50 * math.sqrt(2), -100, 2*50*math.sqrt(2), 'yellow' )
    tl.left(90)
    triangle(1.75*50 * math.sqrt(2), 0, 100, 'blue' )
    tl.left(180)
    triangle(-50, 0, 50*math.sqrt(2), 'pink' )
    tl.right(135)
    triangle(-50, -50, 50*math.sqrt(2), 'purple')
    tl.left(135)
    parallelogram(0, 0, 50*math.sqrt(2) , 'green')
tl.done()
